from django.urls import path

from .views import (
    assign_quiz_view,
    approve_quiz_view,
    annotations_comparison_page,
    annotations_dashboard_page,
    annotations_export_csv,
    annotations_export_json,
    attempt_detail,
    compare_page,
    create_quiz,
    dashboard,
    document_detail,
    moderate_api,
    moderate_page,
    research_artifact_view,
    research_dashboard_page,
    quiz_detail,
    quizzes_page,
    reject_quiz_view,
    report_page,
    submit_quiz_review_view,
    take_quiz,
    traceability_page,
    visualize_page,
)

urlpatterns = [
    path("", dashboard, name="demo-dashboard"),
    path("research/", research_dashboard_page, name="demo-research-dashboard"),
    path(
        "research/artifacts/<path:artifact_path>/",
        research_artifact_view,
        name="demo-research-artifact",
    ),
    path("documents/<int:document_id>/", document_detail, name="demo-document-detail"),
    path("compare/", compare_page, name="demo-compare"),
    path("visualize/", visualize_page, name="demo-visualize"),
    path("trace/<int:comparison_id>/", traceability_page, name="demo-traceability"),
    path("annotations/", annotations_dashboard_page, name="demo-annotations-dashboard"),
    path(
        "annotations/comparisons/<int:comparison_id>/",
        annotations_comparison_page,
        name="demo-annotations-comparison",
    ),
    path(
        "annotations/export.json",
        annotations_export_json,
        name="demo-annotations-export-json",
    ),
    path(
        "annotations/export.csv",
        annotations_export_csv,
        name="demo-annotations-export-csv",
    ),
    path("moderate/", moderate_page, name="demo-moderate"),
    path("api/moderate/", moderate_api, name="demo-moderate-api"),
    path("compare/create-quiz/", create_quiz, name="demo-create-quiz"),
    path("quizzes/", quizzes_page, name="demo-quizzes"),
    path("quizzes/<int:quiz_id>/", quiz_detail, name="demo-quiz-detail"),
    path(
        "quizzes/<int:quiz_id>/submit-review/",
        submit_quiz_review_view,
        name="demo-submit-review-quiz",
    ),
    path(
        "quizzes/<int:quiz_id>/approve/",
        approve_quiz_view,
        name="demo-approve-quiz",
    ),
    path(
        "quizzes/<int:quiz_id>/reject/",
        reject_quiz_view,
        name="demo-reject-quiz",
    ),
    path(
        "quizzes/<int:quiz_id>/assign/",
        assign_quiz_view,
        name="demo-assign-quiz",
    ),
    path("quizzes/<int:quiz_id>/take/", take_quiz, name="demo-take-quiz"),
    path("quizzes/<int:quiz_id>/report/", report_page, name="demo-report"),
    path("attempts/<int:attempt_id>/", attempt_detail, name="demo-attempt-detail"),
]
