# Generated by Django 5.2.12 on 2026-03-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_quizattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extraction_method", models.CharField(default="rule_based", max_length=32)),
                ("entities", models.JSONField(default=list)),
                ("entities_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="documents.chunk",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_id", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chunkanalysis",
            index=models.Index(
                fields=["chunk", "extraction_method"],
                name="documents_c_chunk_i_6f4d4f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chunkanalysis",
            constraint=models.UniqueConstraint(
                fields=("chunk", "extraction_method"),
                name="uniq_chunk_analysis_method",
            ),
        ),
    ]