# Generated by Django 5.2.12 on 2026-03-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_chunkanalysis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chunkanalysis',
            new_name='documents_c_chunk_i_8e1847_idx',
            old_name='documents_c_chunk_i_6f4d4f_idx',
        ),
    ]
