# Generated by Django 5.2.12 on 2026-03-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_documents_c_chunk_i_6f4d4f_idx_documents_c_chunk_i_8e1847_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('open_text', 'Открытый ответ'), ('single_choice', 'Один вариант')], default='open_text', max_length=32)),
                ('prompt', models.TextField()),
                ('correct_text_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersionChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Добавлено'), ('removed', 'Удалено'), ('modified', 'Изменено'), ('moved', 'Перемещено')], max_length=16)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('match_reason', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VersionComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('archived', 'Архив')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена')], default='completed', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('version', 'chunk_index'), name='uniq_chunk_per_version_index'),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_items', to='documents.quizattempt'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='documents.choice'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='documents.employee'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.generatedquiz'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='documents.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='documents.question'),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quizzes', to='documents.summary'),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='new_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_items_new', to='documents.chunk'),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='old_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_items_old', to='documents.chunk'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_change_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='documents.versionchangeitem'),
        ),
        migrations.AddField(
            model_name='versioncomparison',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='documents.document'),
        ),
        migrations.AddField(
            model_name='versioncomparison',
            name='from_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_from', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='versioncomparison',
            name='to_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_to', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_items', to='documents.versioncomparison'),
        ),
        migrations.AddField(
            model_name='summary',
            name='comparison',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='documents.versioncomparison'),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quizzes', to='documents.versioncomparison'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_choice_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uniq_question_order_per_quiz'),
        ),
        migrations.AddConstraint(
            model_name='versioncomparison',
            constraint=models.UniqueConstraint(fields=('from_version', 'to_version'), name='uniq_version_comparison_pair'),
        ),
        migrations.AddIndex(
            model_name='versionchangeitem',
            index=models.Index(fields=['comparison', 'change_type'], name='documents_v_compari_478a82_idx'),
        ),
    ]
