# Generated by Django 5.2.12 on 2026-03-17 19:07

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_answer_choice_employee_question_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-version_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='documentversion',
            name='content_type',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=documents.models.document_version_upload_to),
        ),
    ]