# Generated by Django 5.2.12 on 2026-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_alter_documentversion_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="generatedquiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_version", models.F("to_version")), _negated=True
                ),
                name="generated_quiz_versions_must_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedquiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(
                        ("approved_at__isnull", False),
                        models.Q(("approved_by_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="generated_quiz_approval_fields_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), ("completed_at__isnull", False)),
                    models.Q(("status", "in_progress"), ("completed_at__isnull", True)),
                    _connector="OR",
                ),
                name="quiz_attempt_status_matches_completion",
            ),
        ),
        migrations.AddConstraint(
            model_name="versionchangeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("change_type", "added"),
                        ("old_chunk__isnull", True),
                        ("new_chunk__isnull", False),
                    ),
                    models.Q(
                        ("change_type", "removed"),
                        ("old_chunk__isnull", False),
                        ("new_chunk__isnull", True),
                    ),
                    models.Q(
                        ("change_type__in", ["modified", "moved"]),
                        ("old_chunk__isnull", False),
                        ("new_chunk__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="change_item_chunk_shape_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="versioncomparison",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_version", models.F("to_version")), _negated=True
                ),
                name="comparison_versions_must_differ",
            ),
        ),
    ]
