# Generated by Django 6.0.3 on 2026-03-23 17:47

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_document_identity_and_current_version(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    DocumentVersion = apps.get_model('documents', 'DocumentVersion')

    used_keys = set(
        Document.objects.exclude(document_key__isnull=True)
        .exclude(document_key='')
        .values_list('document_key', flat=True)
    )

    for document in Document.objects.order_by('id'):
        base_key = slugify(document.title or '', allow_unicode=True) or 'document'
        candidate = base_key[:160]
        suffix = 2
        while candidate in used_keys:
            suffix_str = f'-{suffix}'
            candidate = f'{base_key[: 160 - len(suffix_str)]}{suffix_str}'
            suffix += 1
        document.document_key = candidate
        used_keys.add(candidate)

        current_version = (
            DocumentVersion.objects.filter(document_id=document.id)
            .order_by('-version_number', '-created_at', '-id')
            .first()
        )
        document.current_version_id = current_version.id if current_version else None
        document.save(update_fields=['document_key', 'current_version'])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_generatedquiz_generated_quiz_versions_must_differ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_key',
            field=models.SlugField(blank=True, editable=False, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='source_revision_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(
            populate_document_identity_and_current_version,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='documents_d_documen_654958_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'effective_date'], name='documents_d_documen_f852e8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['content_hash'], name='documents_d_content_e1a272_idx'),
        ),
    ]
