# Generated by Django 5.2.13 on 2026-04-16 19:18

from django.db import migrations, models


def rebuild_existing_chunk_layer(apps, schema_editor):
    Chunk = apps.get_model("documents", "Chunk")
    DocumentVersion = apps.get_model("documents", "DocumentVersion")
    VersionComparison = apps.get_model("documents", "VersionComparison")

    from documents.domain.text_processing import chunk_by_structure_ru

    # Старые comparison/change-items были materialized относительно прежнего
    # плоского chunk layer. После перехода на новую структурную модель они
    # считаются устаревшими и должны быть пересобраны заново.
    VersionComparison.objects.all().delete()

    for version in DocumentVersion.objects.all().order_by("id"):
        source_text = version.normalized_text or version.extracted_text or ""
        Chunk.objects.filter(version_id=version.id).delete()

        if not source_text.strip():
            continue

        chunk_specs = chunk_by_structure_ru(source_text)
        if not chunk_specs:
            continue

        Chunk.objects.bulk_create(
            [
                Chunk(
                    version_id=version.id,
                    chunk_index=chunk.chunk_index,
                    fragment_type=chunk.fragment_type,
                    structure_level=chunk.structure_level,
                    raw_label=chunk.raw_label,
                    canonical_label=chunk.canonical_label,
                    path_key=chunk.path_key,
                    heading=chunk.heading,
                    section_path=chunk.section_path,
                    text=chunk.text,
                    text_hash=chunk.text_hash,
                )
                for chunk in chunk_specs
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_alter_quizattempt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="canonical_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chunk",
            name="fragment_type",
            field=models.CharField(
                choices=[
                    ("title", "Заголовок"),
                    ("preamble", "Преамбула"),
                    ("section", "Раздел"),
                    ("chapter", "Глава"),
                    ("article", "Статья"),
                    ("point", "Пункт"),
                    ("subpoint", "Подпункт"),
                    ("paragraph", "Абзац"),
                    ("fallback_block", "Fallback-блок"),
                ],
                default="fallback_block",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="path_key",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="chunk",
            name="raw_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chunk",
            name="structure_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["version", "fragment_type"],
                name="documents_c_version_d5f913_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["version", "path_key"], name="documents_c_version_3557fe_idx"
            ),
        ),
        migrations.RunPython(
            code=rebuild_existing_chunk_layer,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
