# Generated by Django 5.2.13 on 2026-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_chunk_canonical_label_chunk_fragment_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="versionchangeitem",
            name="change_item_chunk_shape_valid",
        ),
        migrations.AddField(
            model_name="versionchangeitem",
            name="new_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="versionchangeitem",
            name="old_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="added_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="comparison_unit",
            field=models.CharField(
                choices=[
                    ("chunk", "Структурный фрагмент"),
                    ("document_text", "Документ целиком"),
                ],
                default="chunk",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="identical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="matching_strategy",
            field=models.CharField(default="structural_chunks_v2", max_length=64),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="modified_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="moved_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="removed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="versioncomparison",
            name="unchanged_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="versionchangeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("change_type", "added"),
                        ("old_chunk__isnull", True),
                        ("old_text", ""),
                        models.Q(
                            ("new_chunk__isnull", False),
                            models.Q(("new_text", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("change_type", "removed"),
                        models.Q(
                            ("old_chunk__isnull", False),
                            models.Q(("old_text", ""), _negated=True),
                            _connector="OR",
                        ),
                        ("new_chunk__isnull", True),
                        ("new_text", ""),
                    ),
                    models.Q(
                        ("change_type__in", ["modified", "moved"]),
                        models.Q(
                            ("old_chunk__isnull", False),
                            models.Q(("old_text", ""), _negated=True),
                            _connector="OR",
                        ),
                        models.Q(
                            ("new_chunk__isnull", False),
                            models.Q(("new_text", ""), _negated=True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="change_item_payload_shape_valid",
            ),
        ),
    ]
