# Generated by Django 5.2.13 on 2026-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_versionchangeitem_change_item_chunk_shape_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionchangeitem',
            name='extracted_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='semantic_type',
            field=models.CharField(choices=[('deadline', 'Сроки'), ('document', 'Документы'), ('obligation', 'Обязанности'), ('procedure', 'Процедура'), ('refusal', 'Основания отказа'), ('condition', 'Условия'), ('responsibility', 'Ответственность'), ('informational', 'Информационное'), ('editorial', 'Редакционное'), ('structure', 'Структурное'), ('unclassified', 'Не классифицировано')], default='unclassified', max_length=32),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='significance_label',
            field=models.CharField(choices=[('critical', 'Критично'), ('important', 'Важно'), ('informational', 'Информационно'), ('editorial', 'Редакционно'), ('not_evaluated', 'Не оценено')], default='not_evaluated', max_length=32),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='significance_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='significance_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='versionchangeitem',
            name='significance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='versionchangeitem',
            index=models.Index(fields=['comparison', 'semantic_type'], name='documents_v_compari_183e34_idx'),
        ),
        migrations.AddIndex(
            model_name='versionchangeitem',
            index=models.Index(fields=['comparison', 'significance_label'], name='documents_v_compari_90f49a_idx'),
        ),
        migrations.AddConstraint(
            model_name='versionchangeitem',
            constraint=models.CheckConstraint(condition=models.Q(('significance_score__gte', 0.0), ('significance_score__lte', 1.0)), name='change_item_significance_score_range_valid'),
        ),
    ]
