# Generated by Django 5.2.13 on 2026-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_versionchangeitem_extracted_entities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquiz",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="rejected_by_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="rejection_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="submitted_for_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="superseded_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="generatedquiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending_review", "На проверке"),
                    ("approved", "Утверждён"),
                    ("rejected", "Отклонён"),
                    ("superseded", "Заменён"),
                    ("archived", "Архив"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedquiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "pending_review"), _negated=True),
                    ("submitted_for_review_at__isnull", False),
                    _connector="OR",
                ),
                name="generated_quiz_review_submission_timestamp_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedquiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    models.Q(
                        ("rejected_at__isnull", False),
                        models.Q(("rejected_by_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="generated_quiz_rejection_fields_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedquiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "superseded"), _negated=True),
                    ("superseded_at__isnull", False),
                    _connector="OR",
                ),
                name="generated_quiz_superseded_timestamp_required",
            ),
        ),
    ]
