# Generated by Django 5.2.13 on 2026-04-22 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_generatedquiz_rejected_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="quizattempt",
            name="quiz_attempt_status_matches_completion",
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="answered_questions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="correct_answers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="score_percent",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "completed"),
                        ("submitted_at__isnull", False),
                        ("completed_at__isnull", False),
                    ),
                    models.Q(
                        ("status", "in_progress"),
                        ("submitted_at__isnull", True),
                        ("completed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="quiz_attempt_status_matches_completion",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")),
                fields=("quiz", "participant_name"),
                name="uniq_active_attempt_per_quiz_participant",
            ),
        ),
    ]
