# Generated by Django 5.2.14 on 2026-05-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_quizassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.CharField(max_length=64)),
                ('original_label', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('minor', 'Minor'), ('ignored', 'Ignored')], max_length=32)),
                ('corrected_label', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('minor', 'Minor'), ('ignored', 'Ignored')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(auto_now_add=True)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_from', to='documents.documentversion')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_changes', to=settings.AUTH_USER_MODEL)),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_to', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-moderated_at', '-id'],
                'indexes': [models.Index(fields=['from_version', 'to_version'], name='documents_m_from_ve_79905d_idx'), models.Index(fields=['change_id'], name='documents_m_change__48af95_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_version', 'to_version', 'change_id'), name='uniq_moderated_change_per_pair_and_change'), models.CheckConstraint(condition=models.Q(('from_version', models.F('to_version')), _negated=True), name='moderated_change_versions_must_differ')],
            },
        ),
    ]
