# Generated by Django 5.2.14 on 2026-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_moderatedchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RusLawODDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pravo_gov_ru_nd', models.CharField(db_index=True, max_length=64, unique=True)),
                ('heading', models.CharField(blank=True, max_length=1024)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('source_xml', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('version_family_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['version_family_key', 'document_date', 'pravo_gov_ru_nd'],
                'indexes': [models.Index(fields=['version_family_key', 'document_date'], name='documents_r_version_308a6a_idx')],
            },
        ),
    ]
