# Generated by Django 5.2.13 on 2026-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0019_ruslawoddocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruslawoddocument",
            name="heading",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="Заголовок документа"
            ),
        ),
    ]
