# Generated by Django 5.2.13 on 2026-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0020_alter_ruslawoddocument_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruslawoddocument",
            name="cleaned_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Очищенный текст"
            ),
        ),
    ]
