# Generated by Django 5.2.14 on 2026-05-19 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_manualdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldChangeAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_semantic_type', models.CharField(blank=True, choices=[('deadline', 'Сроки'), ('document', 'Документы'), ('obligation', 'Обязанности'), ('procedure', 'Процедура'), ('refusal', 'Основания отказа'), ('condition', 'Условия'), ('responsibility', 'Ответственность'), ('informational', 'Информационное'), ('editorial', 'Редакционное'), ('structure', 'Структурное'), ('unclassified', 'Не классифицировано')], max_length=32)),
                ('corrected_significance_label', models.CharField(blank=True, choices=[('critical', 'Критично'), ('important', 'Важно'), ('informational', 'Информационно'), ('editorial', 'Редакционно'), ('not_evaluated', 'Не оценено')], max_length=32)),
                ('corrected_requires_manual_review', models.BooleanField(blank=True, null=True)),
                ('relevance', models.CharField(choices=[('relevant', 'Relevant'), ('not_relevant', 'Not relevant'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_change_annotations', to=settings.AUTH_USER_MODEL)),
                ('change_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_annotations', to='documents.versionchangeitem')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['change_item', 'annotator'], name='documents_g_change__c30d11_idx')],
                'constraints': [models.UniqueConstraint(fields=('change_item', 'annotator'), name='uniq_gold_change_annotation_per_user')],
            },
        ),
        migrations.CreateModel(
            name='GoldQuizAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_label', models.CharField(choices=[('good', 'Good'), ('partially_correct', 'Partially correct'), ('incorrect', 'Incorrect'), ('irrelevant', 'Irrelevant'), ('ambiguous', 'Ambiguous'), ('unsupported', 'Unsupported')], max_length=32)),
                ('corrected_question_text', models.TextField(blank=True)),
                ('corrected_explanation', models.TextField(blank=True)),
                ('should_keep', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_quiz_annotations', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_annotations', to='documents.question')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['question', 'annotator'], name='documents_g_questio_d42404_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'annotator'), name='uniq_gold_quiz_annotation_per_user')],
            },
        ),
        migrations.CreateModel(
            name='GoldSummaryAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_index', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_label', models.CharField(choices=[('good', 'Good'), ('partially_correct', 'Partially correct'), ('unsupported', 'Unsupported'), ('missing_key_point', 'Missing key point'), ('overemphasized_noise', 'Overemphasized noise')], max_length=32)),
                ('corrected_text', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_summary_annotations', to=settings.AUTH_USER_MODEL)),
                ('source_change_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_summary_annotations', to='documents.versionchangeitem')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_annotations', to='documents.summary')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['summary', 'annotator'], name='documents_g_summary_585216_idx'), models.Index(fields=['source_change_item'], name='documents_g_source__797f77_idx')],
                'constraints': [models.UniqueConstraint(fields=('summary', 'annotator', 'highlight_index'), name='uniq_gold_summary_annotation_per_user_and_highlight')],
            },
        ),
    ]
