#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${1:-http://127.0.0.1:8000}"
PYTHON_BIN="${PYTHON_BIN:-python}"

tmp_txt="$(mktemp /tmp/phase5_smoke_XXXXXX.txt 2>/dev/null || mktemp -t phase5_smoke_XXXXXX.txt)"

cleanup() {
  rm -f "$tmp_txt"
}
trap cleanup EXIT

printf 'Smoke line 1\n\nSmoke line 2\n' >"$tmp_txt"

# Для Git Bash / Windows curl нужен путь, который он умеет открыть
upload_path="$tmp_txt"
if command -v cygpath >/dev/null 2>&1; then
  upload_path="$(cygpath -am "$tmp_txt")"
fi

echo "[1/6] health"
curl -fsS "$BASE_URL/api/health/" >/dev/null

echo "[2/6] demo dashboard"
curl -fsS "$BASE_URL/demo/" >/dev/null

echo "[3/6] create document"
document_json="$(
  curl -fsS \
    -X POST \
    "$BASE_URL/api/documents/" \
    -H "Content-Type: application/json" \
    -d '{"title":"Smoke ingestion document","description":"Generated by demo_smoke.sh"}'
)"

document_id="$(
  printf '%s' "$document_json" | "$PYTHON_BIN" -c 'import json,sys; print(json.load(sys.stdin)["id"])'
)"

echo "[4/6] upload version"
version_json="$(
  curl -fsS \
    -X POST \
    "$BASE_URL/api/documents/${document_id}/versions/" \
    -F "file=@${upload_path};type=text/plain"
)"

version_id="$(
  printf '%s' "$version_json" | "$PYTHON_BIN" -c 'import json,sys; print(json.load(sys.stdin)["id"])'
)"

echo "[5/6] inspect extracted text payload"
text_json="$(curl -fsS "$BASE_URL/api/versions/${version_id}/text/")"

printf '%s' "$text_json" | "$PYTHON_BIN" -c '
import json
import sys

payload = json.load(sys.stdin)
required = ("extracted_text", "normalized_text", "content_hash")
missing = [key for key in required if not payload.get(key)]

if missing:
    raise SystemExit("Missing or empty ingestion fields: " + ", ".join(missing))
'

echo "[6/6] smoke checks passed"